// Entire browser surface is fixture-backed; no DB, credentials, collection or external HTTP.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import path from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root=new URL('../app/web/',import.meta.url);
const policy=fs.readFileSync(new URL('../app/main.py',import.meta.url),'utf8').match(/Content-Security-Policy'\]="([^"]+)"/)[1];
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
try {
 const page=await browser.newPage({viewport:{width:1200,height:850},hasTouch:true,timezoneId:"Europe/Moscow"}), errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const contents=[
  {id:'one',platform:'instagram',content_type:'reel',published_at:'2026-10-01T10:00:00Z',caption:'Первый ролик: длинное название для проверки переноса и двух строк в списке публикаций без потери текста в истории',preview_url:'https://s.cdninstagram.com/one.svg',platform_content_id:'1'},
  {id:'two',platform:'instagram',content_type:'photo',published_at:'2026-10-02T10:00:00Z',caption:'Второй ролик',platform_content_id:'2'},
  {id:'three',platform:'tiktok',content_type:'video',published_at:'2026-10-03T10:00:00Z',caption:'Третий ролик',platform_content_id:'3'},
 ];
 const rows=contents.map((content,i)=>({content,snapshot:{id:'s'+i,source:i===2?'tiktok_api':'instagram_api',metric_scope:'lifetime',snapshot_status:'confirmed',snapshot_at:'2026-10-05T16:00:00Z',views:[25,0,null][i],likes:[2,null,1][i],shares:0},derived:{average_watch_pct:null}}));
 const account={id:'account',platform:'instagram',username:'fixture'};
 let accountsFixture=[account],tiktokHistory=[];
 const manualRows=[];
 const posted=[]; let experiments=[]; let connected=true; let history=[rows[0].snapshot]; let retention=[]; let accountHistory=[{source:'instagram_api',metric_scope:'current',snapshot_status:'confirmed',snapshot_at:'2026-10-05T16:00:00Z',followers:0,following:2}];
 const summaries=Object.fromEntries(['views','average_watch_pct','completion_rate','share_rate','save_rate','profile_visit_rate','follow_conversion'].map(k=>[k,{n:k==='views'?2:0,mean:k==='views'?12.5:null,median:k==='views'?12.5:null,guardrail:'insufficient_sample'}]));
 await page.route('**/*',async route=>{
  const req=route.request(),url=new URL(req.url()),p=url.pathname;
  if(url.hostname==='s.cdninstagram.com') return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="600" height="800"><rect width="600" height="800" fill="#067462"/></svg>'});
  assert.equal(url.hostname,'127.0.0.1','Unexpected external request');
  if(p.startsWith('/content/') && p.endsWith('/preview')) return route.fulfill({status:404,body:''});
  if(p==='/dashboard'||p.startsWith('/dashboard/assets/')) {
   const name=p==='/dashboard'?'dashboard.html':p.split('/').at(-1);
   return route.fulfill({headers:{'Content-Security-Policy':policy},contentType:name.endsWith('.html')?'text/html':name.endsWith('.css')?'text/css':name.endsWith('.svg')?'image/svg+xml':'text/javascript',body:fs.readFileSync(new URL(name,root))});
  }
  let payload;
  if(req.method()==='POST') {
   assert.ok(['/experiments','/manual-snapshots/import'].includes(p),'Unexpected mutation '+p);
   const body=req.postDataJSON(); posted.push({path:p,body});
   if(p==='/experiments') {payload={...body,id:'experiment',status:'draft'};experiments=[payload];} else payload={};
  } else if(p==='/dashboard/config') payload={display_timezone:'Europe/Moscow',instagram_ready:connected,tiktok_ready:connected};
  else if(p==='/accounts') payload=connected?accountsFixture:[];
  else if(p==='/content') payload=contents;
  else if(p==='/experiments') payload=experiments;
  else if(p==='/accounts/account/history') payload=accountHistory;
  else if(p==='/accounts/tiktok-account/history') payload=tiktokHistory;
  else if(p==='/collectors/status') payload={instagram:{last_success_at:'2026-10-05T16:00:00Z',last_status:'success'},tiktok:{last_status:'failed'}};
  else if(p==='/collectors/runs') payload=[];
  else if(p==='/analytics/content-comparison') {
   const selected=[...rows,...manualRows].filter(r=>contents.some(c=>c.id===r.content.id)&&(!url.searchParams.has('series'))&&(!url.searchParams.has('platform')||r.content.platform===url.searchParams.get('platform'))&&(!url.searchParams.has('source')||r.snapshot.source===url.searchParams.get('source')));
   payload={rows:selected,groups:selected.length?[{group:null,platform:'instagram',source:'instagram_api',metric_scope:'lifetime',snapshot_status:'confirmed',metrics:summaries,sample_size:2,comparable_period:true}]:[]};
  } else if(p==='/analytics/content/one') payload={content:contents[0],latest:[rows[0]]};
  else if(p==='/content/one/history') payload=history;
  else if(p==='/content/one/retention') payload=retention;
  else if(p==='/content/one/experiments') payload={links:[]};
  else if(p==='/analytics/content/one/velocity') payload={source:'instagram_api',points:[1,6,24,48,72].map(age=>({requested_age_hours:age,actual_age_hours:102,deviation_hours:102-age,views:25,snapshot_at:'2026-10-05T16:00:00Z'}))};
  else assert.fail('Unexpected fixture request '+p);
  await route.fulfill({json:payload});
 });
 const section=name=>page.locator(`[data-view="${name}"]`).first();
 const shot=async name=>{if(process.env.UX_SCREENSHOT_DIR) await page.screenshot({path:path.join(process.env.UX_SCREENSHOT_DIR,name+'.png'),fullPage:true});};
 await page.goto('http://127.0.0.1:8770/dashboard');
 await page.locator('#account-cards .observation-card').first().waitFor();
 assert.equal(await page.locator('#view-overview .publication-card').count(),0);
 assert.equal(await page.locator('#filter-disclosure').isVisible(),false);
 await page.locator('#account-cards').getByRole('img',{name:'Instagram',exact:true}).waitFor();
 await page.locator('#account-cards').getByText('Пока данные только за одну неделю').waitFor();
 accountHistory.push({...accountHistory[0],snapshot_at:'2026-10-06T16:00:00Z',followers:2,following:4}, {...accountHistory[0],snapshot_at:'2026-09-14T16:00:00Z',followers:3}, {...accountHistory[0],snapshot_at:'2026-09-21T16:00:00Z',followers:0});
 await page.locator('#refresh').click();
 await page.locator('#account-cards .account-week').nth(3).getByText('2',{exact:true}).waitFor();
 accountHistory.push(...[1,2,3,4,5].map(day=>({...accountHistory[0],metric_scope:'range',snapshot_status:'estimated',snapshot_at:'2026-10-06T17:00:00Z',source_period_start:`2026-10-0${day}T00:00:00Z`,source_period_end:`2026-10-0${day+1}T00:00:00Z`,followers:null,views:day===5?21:day===4?7:40,likes:day===5?2:4,comments:day===4?0:1,shares:0,saves:0})),{...accountHistory[0],source:'instagram_ui',snapshot_at:'2026-10-06T18:00:00Z',followers:999});
 await page.locator('#refresh').click();
 const netChanges=page.locator('#account-changes .daily-metrics-table').first();
 await netChanges.locator('tbody tr').nth(8).waitFor();
 assert.equal(await page.locator('#account-changes table').count(),1);
 assert.equal(await page.locator('#account-activity-section').count(),0);
 assert.equal(await page.locator('#account-cards .observation-card').count(),1);
 assert.equal(await page.locator('#account-cards .account-timeline').count(),1);
 assert.equal(await page.locator('#account-cards .metric-value').first().innerText(),'2');
 await page.locator('#last-update > p').getByText('Последнее обновление данных: 06.10.2026, 20:00',{exact:true}).waitFor();
 assert.equal(await page.locator('#account-cards option[value=following]').count(),0);
 assert.equal(await page.locator('#view-overview').getByText('Аккаунт подписан на',{exact:true}).count(),0);
 assert.equal(await page.locator('#account-cards .week-change').count(),0);
 await page.getByRole('heading',{name:'Динамика показателей по дням',exact:true}).waitFor();
 const row=date=>netChanges.locator('tbody tr').filter({has:page.getByRole('cell',{name:date,exact:true})});
 assert.deepEqual((await row('06.10.2026').locator('td').allTextContents()).slice(0,7),['06.10.2026','+2','Нет данных','Нет данных','Нет данных','Нет данных','Нет данных']);
 assert.deepEqual((await row('04.10.2026').locator('td').allTextContents()).slice(0,7),['04.10.2026','Нет сравнения','7','4','0','0','0']);
 assert.equal(await row('05.10.2026').locator('td').nth(2).innerText(),'21');
 assert.equal(await row('21.09.2026 → 05.10.2026').locator('td').nth(1).innerText(),'0');
 assert.equal(await row('21.09.2026 → 05.10.2026').locator('td').nth(2).innerText(),'Нет данных');
 assert.equal(await row('14.09.2026 → 21.09.2026').locator('td').nth(1).innerText(),'-3');
 assert.equal(await row('14.09.2026').locator('td').nth(1).innerText(),'Нет сравнения');
 assert.equal(await page.locator('#account-changes').getByText('999',{exact:true}).count(),0);
 const insights=netChanges;
 assert.equal(await page.locator('#account-cards').getByText('Замеры числами',{exact:false}).count(),0);
 const weeks=page.locator('#account-cards .account-week');
 assert.equal(await weeks.count(),4);
 assert.deepEqual(await weeks.locator('.account-week-value').allTextContents(),['3','0','—','2']);
 assert.equal(await weeks.nth(1).locator('rect').getAttribute('height'),'0');
 assert.equal(await weeks.nth(2).locator('rect').count(),0);
 await weeks.nth(2).getByText('Нет данных',{exact:true}).waitFor();
 assert.deepEqual(await weeks.nth(3).locator('.week-date').allTextContents(),['05.10.2026 –','11.10.2026']);
 assert.equal(await page.locator('#account-cards .account-week-bar circle').count(),0);
 assert.equal(await page.locator('#account-cards option[value=views]').count(),0);
 assert.deepEqual(await netChanges.locator('thead th').allTextContents(),['Дата','Изменение подписчиков','Просмотры за день','Лайки за день','Комментарии за день','Репосты за день','Сохранения за день']);
 assert.equal(await page.locator('#view-overview').getByText('Между последними замерами дней',{exact:true}).count(),0);
 assert.equal(await page.locator('#account-cards .metric-value').count(),1);
 await page.locator('#account-cards .account-metric-select select').selectOption('followers');

 // Final view includes the two actual connector shapes, with synthetic account data.
 const current=accountHistory[0];
 accountHistory=[...[[3,0],[4,0],[5,3],[6,3]].map(([day,followers])=>({...current,snapshot_at:`2026-10-0${day}T16:00:00Z`,followers})),
 ...[[3,0,0,0],[4,7,4,1],[5,21,2,0]].map(([day,views,likes,comments])=>({...current,followers:null,metric_scope:'range',snapshot_status:'estimated',snapshot_at:'2026-10-06T17:00:00Z',source_period_start:`2026-10-0${day}T00:00:00Z`,source_period_end:`2026-10-0${day}T23:59:59Z`,views,likes,comments,shares:0,saves:0}))];
 accountsFixture=[account,{id:'tiktok-account',platform:'tiktok',username:'tiktok.fixture'}];
 tiktokHistory=[3,4,5,6].map(day=>({...current,source:'tiktok_api',snapshot_at:`2026-10-0${day}T16:00:00Z`,followers:0,likes:2}));
 await page.locator('#refresh').click();
 await page.locator('#account-changes table').nth(1).waitFor();
 assert.equal(await page.locator('#account-changes table').count(),2);
 assert.ok(await netChanges.evaluate(el=>el.scrollWidth<=el.clientWidth),'Daily table must fit desktop without hidden columns');
 assert.equal(await row('03.10.2026').locator('td').nth(1).innerText(),'Нет сравнения');
 assert.equal(await row('04.10.2026').locator('td').nth(1).innerText(),'0');
 assert.equal(await row('04.10.2026').locator('td').nth(2).innerText(),'7');
 assert.equal(await row('05.10.2026').locator('td').nth(1).innerText(),'+3');
 assert.equal(await row('05.10.2026').locator('td').nth(2).innerText(),'21');
 const tt=page.locator('#account-changes .daily-metrics-table').nth(1);
 assert.deepEqual(await tt.locator('thead th').allTextContents(),['Дата','Изменение подписчиков']);
 const igColumns=await netChanges.locator('thead th').evaluateAll(cells=>cells.slice(0,2).map(cell=>({x:cell.getBoundingClientRect().x,width:cell.getBoundingClientRect().width})));
 const ttColumns=await tt.locator('thead th').evaluateAll(cells=>cells.map(cell=>({x:cell.getBoundingClientRect().x,width:cell.getBoundingClientRect().width})));
 for(let i=0;i<2;i++) assert.ok(Math.abs(igColumns[i].width-ttColumns[i].width)<1);
 assert.ok(ttColumns[0].x>igColumns[1].x,'Desktop daily tables sit alongside each other');
 assert.ok((await tt.boundingBox()).width<(await netChanges.boundingBox()).width/2,'TikTok table should occupy only its two columns');
 assert.equal(await tt.locator('tbody tr').first().locator('td').nth(1).innerText(),'0');
 await page.getByText('Дневные просмотры и реакции TikTok не поступают.',{exact:false}).waitFor();

 assert.equal(await page.locator('.collector-management').getAttribute('open'),null);
 await page.locator('#last-update').getByText('Последний сбор завершился с ошибкой; показаны сохранённые данные',{exact:true}).waitFor();
 await shot('ux-overview-desktop');
 if(process.env.UX_SCREENSHOT_DIR) await page.locator('#account-changes-section').screenshot({path:path.join(process.env.UX_SCREENSHOT_DIR,'daily-changes-desktop.png')});
 await page.setViewportSize({width:390,height:844});
 await page.waitForFunction(()=>!document.getElementById('filter-disclosure').open);
 await page.evaluate(()=>window.scrollTo(0,0));
 const firstCount=await page.locator('#account-cards .metric-value').first().boundingBox();
 assert.ok(firstCount.y>=0&&firstCount.y+firstCount.height<844,`First counter below mobile fold: ${JSON.stringify(firstCount)}`);
 assert.equal(await page.evaluate(()=>window.scrollY),0);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await page.locator('#account-cards .account-week-scroll').first().focus(); await page.keyboard.press('ArrowRight');
 await shot('ux-overview-mobile');
 await netChanges.focus();await page.keyboard.press('ArrowRight');
 await insights.focus();await page.keyboard.press('ArrowRight');
 assert.ok(await insights.evaluate(el=>el.scrollWidth>el.clientWidth));
 await insights.evaluate(el=>el.scrollLeft=0);
 if(process.env.UX_SCREENSHOT_DIR) await netChanges.screenshot({path:path.join(process.env.UX_SCREENSHOT_DIR,'daily-changes-mobile.png')});
 if(process.env.UX_SCREENSHOT_DIR) await page.locator('#account-cards .account-timeline').first().screenshot({path:path.join(process.env.UX_SCREENSHOT_DIR,'weekly-chart-mobile.png')});
 await page.setViewportSize({width:320,height:740});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await shot('ux-overview-small-mobile');
 if(process.env.UX_SCREENSHOT_DIR) await page.locator('#account-cards .account-timeline').first().screenshot({path:path.join(process.env.UX_SCREENSHOT_DIR,'weekly-chart-small-mobile.png')});
 await page.setViewportSize({width:1200,height:850});
 await section('content').click();
 assert.equal(await section('content').getAttribute('aria-current'),'page');
 await page.locator('#content-sort').selectOption('views');
 assert.ok((await page.locator('#content-table tbody tr').first().innerText()).includes('Первый ролик'));
 await page.locator('#content-sort').selectOption('date');
 assert.ok((await page.locator('#content-table tbody tr').first().innerText()).includes('Третий ролик'));
 rows.push({content:contents[0],snapshot:{...rows[0].snapshot,source:'instagram_ui',metric_scope:'range',source_period_start:'2026-10-03T00:00:00Z',source_period_end:'2026-10-04T00:00:00Z',snapshot_status:'estimated',snapshot_at:'2026-10-04T16:00:00Z',views:10},derived:{}});
 await page.locator('#refresh').click();
 await page.waitForFunction(()=>!document.getElementById('refresh').disabled && document.querySelectorAll('#content-table tbody tr').length===3);
 assert.equal(await page.locator('#content-table tbody tr').count(),3);
 assert.equal(await page.locator('#content-table .title-link').count(),3);
 assert.equal(await page.locator('#content-full-table tbody tr').count(),3);
 assert.equal(await page.locator('#content-table').getByText('Instagram Insights',{exact:false}).count(),0);
 assert.equal(await page.locator('#content-count').innerText(),'3 публикаций');
 await page.locator('#filter-disclosure > summary').click();
 await page.locator('.additional-filters > summary').click();
 await page.locator('#filter-source').selectOption('instagram_ui');
 await page.locator('#filters button[type=submit]').click();
 await page.locator('#content-table').getByText('Instagram Insights',{exact:false}).waitFor();
 assert.equal(await page.locator('#content-table tbody tr').count(),1);
 assert.equal(await page.locator('#content-table').getByText('Значение оценено',{exact:true}).isVisible(),true);
 await page.locator('#reset-filters').click();
 await page.waitForFunction(()=>!document.getElementById('refresh').disabled && document.querySelectorAll('#content-table tbody tr').length===3);
 await page.locator('.additional-filters > summary').click();

 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 const card=page.locator('#content-cards .publication-card').filter({hasText:'Первый ролик'}).first();
 await card.scrollIntoViewIfNeeded();
 const icon=card.getByRole('img',{name:'Instagram',exact:true});
 assert.equal(await icon.getAttribute('title'),'Instagram');
 await icon.focus();
 assert.equal(await icon.evaluate(el=>el===document.activeElement),true);
 assert.equal(await page.locator('#filter-platform option[value=instagram]').textContent(),'Instagram');
 assert.equal(await card.locator('.data-details').count(),0);
 assert.ok((await card.locator('.period-label').innerText()).includes('Instagram API'));
 const dataSummary=page.locator('#view-notes > summary');
 await dataSummary.focus(); await page.keyboard.press('Enter');
 await page.locator('#view-notes-body > details > summary').click();
 await page.locator('#view-notes-body table').getByText('Instagram API',{exact:false}).first().waitFor({state:'visible'});
 await dataSummary.tap();
 assert.equal(await page.locator('#view-notes-body').isVisible(),false);
 const title=await card.locator('.title-link').boundingBox(), metric=await card.locator('.metric-value').first().boundingBox();
 assert.ok(title.width>0&&metric.width>0&&metric.y-title.y<300);
 assert.equal((await card.locator('.metric-value').first().innerText()),'25');
 assert.equal(await page.locator('#content-cards .publication-card').filter({hasText:'Первый ролик'}).count(),1);
 assert.ok((await card.locator('.period-label').innerText()).includes('Всего'));
 assert.equal(await card.locator('.collection-mark').count(),0);
 assert.equal(await page.locator('[data-collection-mode=automatic]').count(),1);
 assert.equal(await page.locator('#collection-note img').getAttribute('alt'),'');
 assert.equal(await page.locator('#collection-note img').evaluate(el=>el.complete&&el.naturalWidth>0),true);
 await page.locator('#last-update > p').getByText('Последнее обновление данных:',{exact:false}).waitFor();
 await shot('ux-content-mobile');
 await page.locator('#content-display').selectOption('chart');
 const panels=page.locator('#publication-chart .publication-panel');
 assert.equal(await panels.count(),2);
 const zeroBar=page.locator('#publication-chart .publication-bar').filter({hasText:'Второй ролик'});
 assert.equal(await zeroBar.locator('meter').getAttribute('min'),'0');
 assert.equal(await zeroBar.locator('.bar-value').innerText(),'0');
 const missingBar=page.locator('#publication-chart .publication-bar').filter({hasText:'Третий ролик'});
 assert.equal(await missingBar.locator('meter').count(),0);
 assert.ok((await missingBar.innerText()).includes('Нет данных'));
 assert.ok(!(await page.locator('#publication-chart').innerText()).includes('Значение оценено'));
 assert.ok((await page.locator('#publication-chart').innerText()).includes('Возраст при измерении: 102 ч.'));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await shot('ux-bars-mobile');
 await page.locator('#content-chart-metric').selectOption('completion_rate');
 assert.equal(await page.locator('#publication-chart meter').count(),0);
 rows[0].derived.average_watch_pct=120;
 rows[1].derived.average_watch_pct=0;
 await page.locator('#content-chart-metric').selectOption('average_watch_pct');
 await page.locator('#refresh').click();
 await page.locator('#publication-chart .bar-value').getByText('120%',{exact:true}).waitFor();
 assert.equal(await page.locator('#publication-chart meter').count(),2);
 assert.equal(await page.locator('#publication-chart meter').first().getAttribute('max'),'120');
 assert.equal(await page.locator('#publication-chart .publication-bar').filter({hasText:'Первый ролик'}).first().locator('.bar-value').innerText(),'120%');
 assert.equal(await zeroBar.locator('.bar-value').innerText(),'0%');
 rows[0].derived.average_watch_pct=null; rows[1].derived.average_watch_pct=null;
 await page.locator('#content-display').selectOption('list');
 await card.locator('.title-link').click();
 await page.locator('#velocity-table').getByText('Нет измерений в целевые часы.',{exact:false}).waitFor();
 await page.locator('.missing-windows > summary').click();
 await page.locator('#velocity-table').getByText('В это время измерение не сохранено').first().waitFor();
 assert.equal(await page.locator('#detail-title').innerText(),contents[0].caption);
 await page.locator('#detail-context').getByRole('img',{name:'Instagram',exact:true}).waitFor();
 assert.ok(!(await page.locator('#velocity-table .window-readings').innerText()).includes('25'));
 await page.locator('#velocity-table > details:not(.missing-windows) > summary').click();
 assert.ok((await page.locator('#velocity-table > details:not(.missing-windows)').innerText()).includes('102'));
 await page.locator('#velocity-table > details:not(.missing-windows) > summary').click();
 await shot('ux-history-mobile');
 await page.locator('#growth-chart').getByText('Одно измерение — тренд пока не виден.',{exact:true}).waitFor();
 assert.equal(await page.locator('#growth-chart .history-plot circle').count(),1);
 await page.locator('#detail-derived > details > summary').click();
 await page.locator('#detail-derived table').waitFor({state:'visible'});
 await page.locator('#detail-back').click();
 retention=[{source:'instagram_ui',metric_scope:'lifetime',snapshot_status:'confirmed',snapshot_at:'2026-10-05T16:00:00Z',average_watch_seconds:12.5}];
 history=[...history,
  {...rows[0].snapshot,id:'early-zero',snapshot_at:'2026-10-01T12:00:00Z',views:0},
  rows.at(-1).snapshot,
  {...rows[0].snapshot,id:'missing',snapshot_at:'2026-10-02T12:00:00Z',views:null}];
 await card.locator('.title-link').click();
 const growth=page.locator('#growth-chart');
 await growth.locator('.chart-values summary').getByText('Измерения числами (3)',{exact:true}).waitFor();
 assert.equal(await growth.locator('.plot-legend > li').count(),2);
 assert.equal(await growth.locator('.history-plot circle').count(),2);
 assert.equal(await growth.locator('.history-plot rect').count(),1);
 for(const shape of ['circle','rect']) {
  assert.equal(await growth.locator('.history-plot '+shape).first().getAttribute('fill'),await growth.locator('.series-marker '+shape).getAttribute('fill'));
 }
 const chartSummary=growth.locator('.chart-values summary');
 await chartSummary.focus(); await page.keyboard.press('Enter');
 await growth.getByText('Серия 1 · через 2 ч. · 0 просмотров',{exact:true}).waitFor({state:'visible'});
 await growth.getByText('Серия 2 · через 78 ч. · 10 просмотров',{exact:true}).waitFor({state:'visible'});
 assert.ok(parseFloat(await growth.locator('.history-plot text').first().evaluate(el=>getComputedStyle(el).fontSize))>=13);
 assert.equal(await growth.locator('.history-plot path').count(),0);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 assert.equal(await growth.locator('.collection-mark[data-collection-mode=automatic]').count(),0);
 assert.equal(await page.locator('[data-collection-mode=automatic]').count(),1);
 assert.equal(await growth.locator('.collection-mark[data-collection-mode=manual]').count(),0);
 assert.equal(await page.locator('#detail-history .collection-mark[data-collection-mode=manual]').count(),0);
 assert.equal(await page.locator('#detail-metrics .collection-mark').count(),0);
 assert.equal(await page.locator('#retention-table .collection-mark').count(),0);
 await page.locator('#retention-table').getByText('Подтверждено',{exact:true}).waitFor();
 assert.equal(await page.locator('#tags-form').locator('..').locator('summary .collection-mark').innerText(),'AI-агент / самостоятельно');
 await shot('ux-history-multiple-mobile');
 await chartSummary.tap();
 assert.equal(await growth.locator('.measured-points').isVisible(),false);
 await page.setViewportSize({width:1200,height:850});
 await shot('ux-history-desktop');
 await page.setViewportSize({width:390,height:844});
 await page.locator('#detail-back').click();
 await page.locator('#filter-disclosure > summary').click();
 await page.locator('.additional-filters > summary').click();
 await page.locator('#filter-series').fill('Несуществующая серия');
 await page.locator('#filters button[type=submit]').click();
 await page.locator('#content-cards').getByText('По этим фильтрам публикаций не найдено').waitFor();
 assert.ok(!(await page.locator('#content-cards').innerText()).includes('подключ'));
 assert.ok((await page.locator('#content-cards').innerText()).includes('Несуществующая серия'));
 await page.locator('#content-cards').getByRole('button',{name:'Сбросить фильтры'}).click();
 await page.locator('#content-cards .publication-card').first().waitFor();
 assert.equal(await page.locator('#filter-series').inputValue(),'');
 await section('comparison').click();
 await page.locator('#comparison-platforms').getByRole('button',{name:'Instagram',exact:true}).click();
 await page.locator('#comparison-source').selectOption('instagram_api');
 await page.locator('#comparison-cards .comparison-row').first().waitFor();
 assert.equal(await page.locator('#comparison-cards .comparison-row').count(),1);
 assert.equal(await page.locator('#comparison-cards .comparison-value').first().innerText(),'25');
 assert.equal(await page.locator('#comparison-table').count(),0);
 assert.equal(await page.locator('#filter-disclosure').isVisible(),false);
 await page.locator('#comparison-group').selectOption('hook_type');
 await page.locator('#comparison-cards').getByText('Без тега',{exact:true}).waitFor();
 await page.locator('#comparison-cards summary').first().click();
 await page.locator('#comparison-cards .comparison-members button').first().waitFor();
 assert.ok((await page.locator('#view-notes-body').textContent()).includes('меньше 5'));
 assert.ok(!(await page.locator('#comparison-insight').innerText()).includes('меньше 5'));
 await page.locator('#comparison-format').selectOption('Фото');
 assert.equal(await page.locator('#comparison-cards .comparison-value').first().innerText(),'0');
 assert.equal(await page.locator('#comparison-cards .comparison-bar').first().evaluate(el=>el.style.width),'0%');
 await page.locator('#comparison-metric').selectOption('completion_rate');
 await page.locator('#comparison-cards').getByText('По этому показателю нет данных',{exact:true}).waitFor();
 await page.locator('#comparison-metric').selectOption('views');
 await page.locator('#comparison-format').selectOption('Короткое видео');
 await page.locator('#comparison-source').selectOption('instagram_ui');
 await page.locator('#comparison-cards').getByText('Нет сопоставимых публикаций',{exact:true}).waitFor();
 await page.locator('#comparison-source').selectOption('instagram_api');
 await page.locator('.comparison-dates > summary').click();
 await page.locator('#comparison-from').fill('2026-10-03');
 await page.locator('#comparison-from').dispatchEvent('change');
 await page.locator('#comparison-cards').getByText('Нет сопоставимых публикаций',{exact:true}).waitFor();
 await page.locator('#comparison-from').fill('');
 await page.locator('#comparison-from').dispatchEvent('change');
 for(const width of [320,768,1024,1440]) {await page.setViewportSize({width,height:850});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);}
 await page.setViewportSize({width:390,height:844});
 await shot('ux-comparison-mobile');
 await page.locator('#comparison-cards').getByRole('button',{name:'Разметить публикации'}).click();
 assert.equal(await section('content').getAttribute('aria-current'),'page');
 await section('experiments').click();
 await page.locator('#view-experiments > details > summary').click();
 await page.locator('#experiment-name').fill('Проверка fixture');
 await page.locator('#experiment-metric').selectOption({label:'Просмотры'});
 await page.locator('#experiment-source').selectOption('instagram_api');
 assert.ok((await page.locator('#experiment-availability').innerText()).includes('2 из 2'));
 await page.locator('#experiment-form button[type=submit]').click();
 await page.locator('#experiment-list').getByText('Проверка fixture',{exact:true}).waitFor();
 assert.equal(posted.find(r=>r.path==='/experiments').body.metric,'views');
 manualRows.push({content:contents[0],snapshot:{id:'manual-one',source:'instagram_ui',metric_scope:'lifetime',snapshot_status:'confirmed',snapshot_at:'2026-10-06T17:00:00Z',views:0,watch_time_avg_seconds:null,completion_rate:null},derived:{}}, {content:contents[2],snapshot:{id:'manual-three',source:'tiktok_studio',metric_scope:'lifetime',snapshot_status:'anomalous',snapshot_at:'2026-10-06T17:00:00Z',views:0,watch_time_avg_seconds:0,completion_rate:50,notes:'Проверенная аномалия fixture'},derived:{}});
 await page.locator('#refresh').click();
 await section('import').click();
 await page.locator('#manual-measurements').getByRole('heading',{name:/TikTok Studio$/}).waitFor();
 const manualTables=page.locator('#manual-measurements table');
 assert.equal(await manualTables.count(),2); // Two publication sources; account fixtures currently contain only API data.
 const manualInstagram=manualTables.nth(0).locator('tbody tr').filter({has:page.getByRole('cell',{name:'0',exact:true})}).first();
 const manualHeaders=await manualTables.nth(0).locator('thead th').allTextContents();
 assert.ok(manualHeaders.includes('Период')); // Mixed lifetime/range fixture keeps essential context.
 assert.equal(await manualInstagram.locator('td').nth(manualHeaders.indexOf('Просмотры')).innerText(),'0');
 assert.equal(await manualInstagram.locator('td').nth(manualHeaders.indexOf('Среднее, сек.')).innerText(),'—');
 await page.locator('#manual-measurements').getByText('Аномалия',{exact:true}).waitFor();
 assert.equal(await page.locator('#manual-measurements details').count(),0);
 assert.equal(await page.locator('#view-notes').count(),1);
 await page.locator('#view-notes > summary').focus(); await page.keyboard.press('Enter');
 await page.locator('#view-notes-body').getByText('Проверенная аномалия fixture',{exact:true}).waitFor();
 assert.equal(await page.locator('#view-notes-body').getByText('Проверенная аномалия fixture',{exact:true}).count(),1);
 for (const width of [320,768,1024,1440]) {
  await page.setViewportSize({width,height:850});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 }
 await page.setViewportSize({width:390,height:844});

 assert.equal(await page.locator('#view-import > .section-heading .collection-mark').innerText(),'Insights / Studio');
 assert.equal(await page.locator('[data-collection-mode=automatic]').count(),1);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await shot('ux-manual-entry-mobile');
 await page.setViewportSize({width:1200,height:850});
 await shot('ux-manual-entry-desktop');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.locator('#observation-form').isVisible(),false);
 await page.locator('.observation-editor > summary').focus(); await page.keyboard.press('Enter');
 assert.equal(await page.locator('#observation-form').isVisible(),true);
 assert.equal(await page.locator('#observation-metrics input[name=watch_time_avg_seconds]').isVisible(),false);
 await page.locator('#observation-metrics input[name=views]').fill('0');
 await page.locator('#observation-metrics').getByText('Время просмотра и досмотр',{exact:true}).click();
 await page.locator('#observation-metrics input[name=watch_time_avg_seconds]').fill('12.5');
 await page.locator('#observation-form button[type=submit]').click();
 await page.locator('#observation-message').getByText('Наблюдение добавлено.',{exact:false}).waitFor();
 const record=posted.find(r=>r.path==='/manual-snapshots/import').body.content_snapshots[0];
 assert.equal(record.views,0); assert.equal(record.watch_time_avg_seconds,'12.5'); assert.equal(record.completion_rate,null);
 // Long histories stay one chart row and retain access to every calendar week.
 await page.setViewportSize({width:1440,height:900});
 accountHistory=Array.from({length:20},(_,i)=>({...current,snapshot_at:new Date(Date.UTC(2026,4,25+i*7,16)).toISOString(),followers:i}));
 await page.locator('#refresh').click(); await section('overview').click();
 const longCard=page.locator('#account-cards > .observation-card').first();
 await longCard.locator('.week-page-range').getByText('Недели 17–20 из 20',{exact:true}).waitFor();
 const headerGeometry=await longCard.evaluate(card=>{
  const b=s=>card.querySelector(s).getBoundingClientRect();
  return {icon:b('.card-heading .platform-mark').y,value:b('.metric-value').y,name:b('.card-heading .platform-context > span:last-child').y,label:b('.metric-label').y};
 });
 assert.ok(Math.abs(headerGeometry.icon-headerGeometry.value)<1);
 assert.ok(Math.abs(headerGeometry.name-headerGeometry.label)<1);
 assert.equal(await longCard.evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');
 assert.ok((await longCard.locator('.metric-value').boundingBox()).height<=36);
 const latestValues=await longCard.locator('.account-week-value').allTextContents();
 assert.deepEqual(latestValues,['16','17','18','19']);
 const latestHeight=await longCard.boundingBox();
 const latestScale=await longCard.locator('rect').last().getAttribute('height');
 await longCard.getByRole('button',{name:'Предыдущие недели',exact:true}).click();
 assert.deepEqual(await longCard.locator('.account-week-value').allTextContents(),['12','13','14','15']);
 assert.ok(Math.abs((await longCard.boundingBox()).height-latestHeight.height)<1);
 await longCard.locator('.account-week-scroll').focus(); await page.keyboard.press('ArrowRight');
 assert.deepEqual(await longCard.locator('.account-week-value').allTextContents(),latestValues);
 assert.equal(await longCard.locator('rect').last().getAttribute('height'),latestScale);
 while(await longCard.getByRole('button',{name:'Предыдущие недели',exact:true}).isEnabled()) await longCard.getByRole('button',{name:'Предыдущие недели',exact:true}).click();
 assert.deepEqual(await longCard.locator('.account-week-value').allTextContents(),['0','1','2','3']);
 assert.equal(await longCard.locator('rect').first().getAttribute('height'),'0');
 while(await longCard.getByRole('button',{name:'Следующие недели',exact:true}).isEnabled()) await longCard.getByRole('button',{name:'Следующие недели',exact:true}).click();
 await shot('weekly-history-desktop');
 for(const width of [390,320]) {
  await page.setViewportSize({width,height:844});
  await page.waitForFunction(()=>document.querySelector('#account-cards .account-week').parentElement.children.length<=3);
  assert.ok(await longCard.locator('.account-week').count()<=3);
  assert.equal(await longCard.locator('.account-week-scroll').evaluate(e=>e.scrollWidth<=e.clientWidth),true);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.ok((await longCard.getByRole('button',{name:'Предыдущие недели',exact:true}).boundingBox()).height>=44);
  await shot('weekly-history-'+width);
 }
 contents.splice(0); await page.reload();
 await section('content').click();
 await page.locator('#content-cards').getByText('Публикаций пока нет',{exact:true}).waitFor();
 assert.ok(!(await page.locator('#content-cards').innerText()).includes('Аккаунт ещё не подключён'));
 connected=false; await page.reload();
 await section('content').click();
 await page.locator('#content-cards').getByText('Аккаунт ещё не подключён',{exact:true}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('UX browser: mobile first counter, filters, comparison cards, separate bar panels, zero/missing values, single/multiple history points, matching legends, keyboard/touch values, late windows, metric/save and empty states passed');
} finally {await browser.close();}
